[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Skip processing for static assets
[build.processing]
  skip_processing = true

# Configure redirects for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
